name: dating
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  page_view_indicators: ^2.0.0
  shared_preferences: ^2.0.15
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.1
  cloud_firestore: ^3.4.2
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.4
  progress_dialog: ^1.2.2
  provider: ^6.0.3
  url_launcher: ^6.0.5
  intl: ^0.17.0
  cached_network_image: ^2.1.0+1
  uuid: ^3.0.6
  video_thumbnail: ^0.5.2
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  video_player: ^2.2.19
  http: ^0.13.4
  location: ^4.4.0
  latlong: ^0.6.1
  smooth_page_indicator: ^1.0.0+2
  flutter_webrtc: ^0.6.3
  firebase_messaging: ^12.0.1
  pin_code_fields: ^7.4.0
  in_app_purchase: ^0.5.2
  wakelock: ^0.6.2
  permission_handler: ^10.0.0
  easy_localization: ^3.0.1
  fluttertoast: ^8.0.9
  modal_progress_hud: ^0.1.3
  percent_indicator: ^4.2.2
  numberpicker: ^2.1.1
  flutter_launcher_icons: ^0.9.3
  mask_text_input_formatter: ^2.4.0





  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  textfield_tags: ^1.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/fever_launcher_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/